FROM wordpress:latest


ENV WORDPRESS_DB_HOST=mysql-container
ENV WORDPRESS_DB_USER=root
ENV WORDPRESS_DB_PASSWORD=password
ENV WORDPRESS_DB_NAME=wordpress


COPY nginx.conf /etc/nginx/conf.d/default.conf


