
FROM openresty/openresty:alpine


ENV OPENRESTY_VERSION=1.19.3.1


RUN apk add --no-cache openssl perl build-base postgresql-dev pcre-dev zlib-dev


RUN wget https://openresty.org/download/openresty-$OPENRESTY_VERSION.tar.gz && \
    tar -xzf openresty-$OPENRESTY_VERSION.tar.gz && \
    rm openresty-$OPENRESTY_VERSION.tar.gz


RUN cd openresty-$OPENRESTY_VERSION && \
    ./configure --prefix=/opt/openresty \
                --with-pcre-jit \
                --with-ipv6 \
                --without-http_redis2_module \
                --with-http_iconv_module \
                --with-http_postgres_module \
                -j$(nproc) && \
    make && \
    make install && \
    cd .. && \
    rm -rf openresty-$OPENRESTY_VERSION


COPY nginx.conf /etc/nginx/default.conf


EXPOSE 80
EXPOSE 443


CMD ["/opt/openresty/nginx/sbin/nginx", "-g", "daemon off;"]
